### ISSUE TITLE
How to use self-signed cert?

### ISSUE THREAD

**Issue by elcolie** [py-pa/django-minio-storage#11]
I use self-signed cert by using ssl

`openssl genrsa -out private.key 1024`
and
`openssl req -new -x509 -days 3650 -key private.key -out public.crt -subj "/C=TH/ST=state/L=location/O=organization/CN=domain"`
Then put the in `.minio`
```
$ pwd
/Users/el/.minio/certs
Sarits-MacBook-Air-2:certs el$ ls
private.key	public.crt
```

**Reference:**
https://github.com/minio/minio/blob/master/docs/configure-minio-with-tls.md#with-generate_certgo-self-signed-certificate

```
Sarits-MacBook-Air-2:uih-portal el$ minio server ~/Pictures/

Endpoint:  https://192.168.11.145:9000  https://127.0.0.1:9000
AccessKey: KBP6WXGPS387090EZMG8
SecretKey: DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A
Region:    us-east-1
SqsARNs:

Browser Access:
   https://192.168.11.145:9000  https://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio https://192.168.11.145:9000 KBP6WXGPS387090EZMG8 DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
2016/11/22 10:46:35 http: TLS handshake error from [::1]:60412: remote error: tls: unknown certificate authority
```

I follow your examples as below:
```
from minio import Minio
from minio.error import ResponseError

MINIO_STORAGE_ACCESS_KEY = "KBP6WXGPS387090EZMG8"
MINIO_STORAGE_SECRET_KEY = "DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A"

client = Minio('localhost:9000',
               access_key=MINIO_STORAGE_ACCESS_KEY,
               secret_key=MINIO_STORAGE_SECRET_KEY,
               secure=True)

# Put an object 'my-objectname' with contents from 'my-filepath'
try:
    client.fput_object('kimbucket', 'joker.jpg', '/Users/el/Pictures/Joker-Wallpaper-09.jpg')
except ResponseError as err:
    print(err)
```

```
$ python fput_object.py
Traceback (most recent call last):
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fput_object.py", line 33, in <module>
    client.fput_object('kimbucket', 'joker.jpg', '/Users/el/Pictures/Joker-Wallpaper-09.jpg')
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 564, in fput_object
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 1434, in _do_put_object
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 1698, in _url_open
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 1644, in _get_bucket_region
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 1673, in _get_bucket_location
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

How can I use self-signed on development computer?

**Comment by elcolie** [comment]
Use `Letsencrypt`
