### ISSUE TITLE
Mediastorage fails when uploading images

### ISSUE THREAD

**Issue by thomasf** [py-pa/django-minio-storage#16]
I don't have time to figure out which of the involved parties I should blame so I'll create an issue about it because I ran out of django_minio time for today....

```py
E0509 17:00:46.331 django.request:135 Internal Server Error: /cms/images/chooser/upload/
Traceback (most recent call last):
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/wagtail/wagtailadmin/decorators.py", line 27, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/wagtail/wagtailadmin/utils.py", line 133, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/wagtail/wagtailimages/views/chooser.py", line 132, in chooser_upload
    form.save()
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/wagtail/wagtailadmin/forms.py", line 387, in save
    return super(BaseCollectionMemberForm, self).save(commit=commit)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/forms/models.py", line 451, in save
    self.instance.save()
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/query.py", line 1061, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    for sql, params in self.as_sql():
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    for obj in self.query.objs
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1051, in <listcomp>
    for obj in self.query.objs
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1050, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1000, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/fields/files.py", line 297, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/fields/files.py", line 96, in save
    setattr(self.instance, self.field.name, self.name)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/fields/files.py", line 378, in __set__
    self.field.update_dimension_fields(instance, force=True)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/db/models/fields/files.py", line 481, in update_dimension_fields
    width = file.width
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/files/images.py", line 19, in width
    return self._get_image_dimensions()[0]
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/files/images.py", line 29, in _get_image_dimensions
    self._dimensions_cache = get_image_dimensions(self, close=close)
  File "/home/thomasf/.virtualenvs/some_project/lib/python3.6/site-packages/django/core/files/images.py", line 45, in get_image_dimensions
    file.seek(0)
io.UnsupportedOperation: seek

```

**Comment by thomasf** [comment]
A small investigation shows that all the involved parties relies on a seekable reader.

When I reworked some code at one place I got the same kind of error further down the chain of libraries, even iside the standard library..

1. wagtail
2. django
3. pillow
4. standard library (imghdr.what)

I'm not sure what's the best action here..

I would expect non seekable streaming io to work in django, maybe there is a
more subtle reason?

**Comment by thomasf** [comment]
In the s3 library below they create a temporary file to allow seeking.. 
It seems a bit wasteful for many situations but maybe it's required for things to work properly.. 
If it's required I would also want a custom storage option to bypass it as well..

https://github.com/etianen/django-s3-storage/blob/master/django_s3_storage/storage.py#L196

**Comment by thomasf** [comment]
Also, the get_object() function in minio-py might require connection clean up in some situations.

```
def get_object(self, bucket_name, object_name):
        """
        Retrieves an object from a bucket.
        This function returns an object that contains an open network
        connection to enable incremental consumption of the
        response. To re-use the connection (if desired) on subsequent
        requests, the user needs to call `release_conn()` on the
        returned object after processing.
```

Fetching into a local temporary does away with this problem as wel..
