### ISSUE TITLE
minio 2.2.2 is not support

### ISSUE THREAD

**Issue by elcolie** [py-pa/django-minio-storage#24]
```python
DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_MEDIA_BUCKET_NAME = 'media'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = 'static'
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
MINIO_STORAGE_ENDPOINT = 'localhost:9000'
MINIO_STORAGE_ACCESS_KEY = 'KBP6WXGPS387090EZMG8'
MINIO_STORAGE_SECRET_KEY = 'DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A'
MINIO_STORAGE_USE_HTTPS = False
```

```bash
python manage.py collectstatic --no-input --settings=uihspot.config.settings.local
I'm running locally.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
    if self.storage.exists(prefixed_path):
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/minio_storage/storage.py", line 95, in exists
    self.client.stat_object(self.bucket_name, self._sanitize_path(name))
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/minio/api.py", line 1045, in stat_object
    object_name=object_name)
  File "/Users/el/.pyenv/versions/uih-spot/lib/python3.6/site-packages/minio/api.py", line 1900, in _url_open
    object_name).get_exception()
minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.
```

In my `requirements.txt`
`django-minio-storage` works well with `minio==2.2.1`, but from this time 30May2017 19:33 GMT+7. `minio==2.2.2` by now and I got bug

**Comment by thomasf** [comment]
Does the bucket exist?

IIRC this is the same situation where I got the error ( https://github.com/py-pa/django-minio-storage/issues/5 )

**Comment by elcolie** [comment]
Bucket does not exist. And the it create `static` bucket and then crash
Then I create all buckets `static` and `media`. Crash occur

**Comment by thomasf** [comment]
It's  probably because of this: https://github.com/minio/minio-py/issues/514

**Comment by Yurmusp** [comment]
It is because of this I think:
https://github.com/minio/minio/issues/4434

It is because django checks folder existence and minio has no concept of folders in it's low level part of implementation.

**Comment by Yurmusp** [comment]
I believe this is the fix.
https://github.com/tomhoule/django-minio-storage/pull/25
