### ISSUE TITLE
Django file object that had seek or read applied fails to be stored 

### ISSUE THREAD

**Issue by Yurmusp** [py-pa/django-minio-storage#26]
It throws exception that it fails to read enough data not reaching right file size.

**Comment by Yurmusp** [comment]
Callstack example.
Traceback (most recent call last):
  File "/opt/web/django-apps/ZZZ_app/tests/test_ZZZ_downloads.py", line 28, in setUp
    release2.save()
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in _save_table
    for f in non_pks]
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 314, in pre_save
    file.save(file.name, file, save=False)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/core/files/storage.py", line 63, in save
    name = self._save(name, content)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/minio_storage/storage.py", line 93, in _save
    content_type)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/minio/api.py", line 894, in put_object
    'Could not read {} bytes from data to upload'.format(length)
InvalidArgumentError: InvalidArgumentError: message: Could not read 24 bytes from data to upload
