### ISSUE TITLE
Running collectstatic twice returns TypeError.

### ISSUE THREAD

**Issue by maikelvl** [py-pa/django-minio-storage#42]
Hi, I found a bug where running Django's `collectstatic` command twice:

```python
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    execute_from_command_line(sys.argv)
  File "/project/env/lib/python/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/project/env/lib/python/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project/env/lib/python/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/env/lib/python/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/project/env/lib/python/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/project/env/lib/python/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/project/env/lib/python/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/project/env/lib/python/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 263, in delete_file
    target_last_modified = self.storage.get_modified_time(prefixed_path)
  File "/project/env/lib/python/site-packages/django/core/files/storage.py", line 230, in get_modified_time
    dt = self.modified_time(name)
  File "/project/src/minio_storage/storage.py", line 231, in modified_time
    return datetime.datetime.fromtimestamp(info.last_modified)
TypeError: an integer is required (got type time.struct_time)
```

This bug also appeared when running the tests as is:

```bash
py35-django111 inst: /Users/maikel/projects/python-packages/django-minio-storage/.tox/dist/django-minio-storage-0.1.1.dev75+g67e6be7.zip
py35-django111 installed: certifi==2017.7.27.1,chardet==3.0.4,coverage==4.4.1,Django==1.11.6,django-minio-storage==0.1.1.dev75+g67e6be7,idna==2.6,minio==2.2.5,mock==2.0.0,pbr==3.1.1,py==1.4.34,pytest==3.1.1,pytest-cov==2.4.0,pytest-django==3.1.2,pytest-pythonpath==0.7.1,pytz==2017.2,requests==2.18.4,six==1.11.0,urllib3==1.22
py35-django111 runtests: PYTHONHASHSEED='1380463971'
py35-django111 runtests: commands[0] | pytest
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.5.2, pytest-3.1.1, py-1.4.34, pluggy-0.4.0
Django settings: django_minio_storage_tests.settings (from ini file)
rootdir: /Users/maikel/projects/python-packages/django-minio-storage, inifile: tox.ini
plugins: pythonpath-0.7.1, django-3.1.2, cov-2.4.0
collected 34 items

tests/test_app/tests/bucket_tests.py ...
tests/test_app/tests/delete_tests.py .
tests/test_app/tests/retrieve_tests.py FF.....F...........
tests/test_app/tests/upload_tests.py ...........

===================================================================================================== FAILURES =====================================================================================================
_______________________________________________________________________________ RetrieveTestsWithRestrictedBucket.test_accessed_time _______________________________________________________________________________
tests/test_app/tests/retrieve_tests.py:61: in test_accessed_time
    self.assertIsInstance(self.media_storage.accessed_time(self.new_file),
minio_storage/storage.py:187: in accessed_time
    return self.modified_time(name)
minio_storage/storage.py:200: in modified_time
    return datetime.datetime.fromtimestamp(info.last_modified)
E   TypeError: a float is required
_______________________________________________________________________________ RetrieveTestsWithRestrictedBucket.test_created_time ________________________________________________________________________________
tests/test_app/tests/retrieve_tests.py:65: in test_created_time
    self.assertIsInstance(self.media_storage.created_time(self.new_file),
minio_storage/storage.py:194: in created_time
    return self.modified_time(name)
minio_storage/storage.py:200: in modified_time
    return datetime.datetime.fromtimestamp(info.last_modified)
E   TypeError: a float is required
_______________________________________________________________________________ RetrieveTestsWithRestrictedBucket.test_modified_time _______________________________________________________________________________
tests/test_app/tests/retrieve_tests.py:57: in test_modified_time
    self.assertIsInstance(self.media_storage.modified_time(self.new_file),
minio_storage/storage.py:200: in modified_time
    return datetime.datetime.fromtimestamp(info.last_modified)
E   TypeError: a float is required
======================================================================================= 3 failed, 31 passed in 1.68 seconds ========================================================================================
ERROR: InvocationError: '/Users/maikel/projects/python-packages/django-minio-storage/.tox/py35-django111/bin/pytest'
_____________________________________________________________________________________________________ summary ______________________________________________________________________________________________________
ERROR:   py35-django111: commands failed
```

**Comment by thomasf** [comment]
is this fixed now?

**Comment by thomasf** [comment]
I've set up travis to do a daily build from master so that we can monitor if new minio releases breaks something.,

**Comment by maikelvl** [comment]
Yes, this is fixed now. Thanks.

Good to know you've set that up. 😄 Good job.
