### ISSUE TITLE
NoSuchKey error on collectstatic

### ISSUE THREAD

**Issue by arashyousefi** [py-pa/django-minio-storage#49]
I'm having trouble collecting staticfiles into minio server. The issue seems to be the `exists` method in `storage.py` which is not catching the thrown exception properly when the file does not exists. Here is the log:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
    if self.storage.exists(prefixed_path):
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/minio_storage/storage.py", line 95, in exists
    self.client.stat_object(self.bucket_name, self._sanitize_path(name))
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/minio/api.py", line 935, in stat_object
    object_name=object_name)
  File "/home/arash/.virtualenvs/lyan/lib/python3.5/site-packages/minio/api.py", line 1781, in _url_open
    object_name).get_exception()
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.
```

**Comment by thomasf** [comment]
Have you tried installing from latest master commit?

**Comment by arashyousefi** [comment]
That seems to be the issue. Thanks!
