### ISSUE TITLE
Syntax error in storage.py

### ISSUE THREAD

**Issue by vncsms** [py-pa/django-minio-storage#91]
I having tried to save a image in my minio server, but when i make a request to store my file, i got this error:

```
Traceback (most recent call last):
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/serializers.py", line 213, in save
    self.instance = self.create(validated_data)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/rest_framework/serializers.py", line 932, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/developer/projects/myprojects/mystore-backend/image/models.py", line 15, in save
    super(Image, self).save(*args, **kwargs)
  File "/home/developer/projects/myprojects/mystore-backend/common/base.py", line 68, in save
    super(UIDModel, self).save(*args, **kwargs)
  File "/home/developer/projects/myprojects/mystore-backend/common/base.py", line 26, in save
    return super(DatedModel, self).save(*args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1367, in execute_sql
    for sql, params in self.as_sql():
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1311, in as_sql
    for obj in self.query.objs
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1311, in <listcomp>
    for obj in self.query.objs
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1310, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1261, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/fields/files.py", line 86, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/db/models/fields/files.py", line 307, in generate_filename
    return self.storage.generate_filename(filename)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/core/files/storage.py", line 363, in _setup
    self._wrapped = get_storage_class()()
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/core/files/storage.py", line 358, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/developer/.virtualenvs/store/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/minio_storage/storage.py", line 52
    **kwargs,
            ^
SyntaxError: invalid syntax

```

My python is 3.5.

I also have checked the file with flake 8.
```
...
/home/developer/.virtualenvs/store/lib/python3.5/site-packages/minio_storage/storage.py:52:17: E999 SyntaxError: invalid syntax
...
```

I removed `,` but still getting anothers syntax error:
```
File "/home/developer/.virtualenvs/store/lib/python3.5/site-packages/minio_storage/storage.py", line 209
    dirs: T.List[str] = []
```

Is there a specific version of the python to user?

**Comment by thomasf** [comment]
We run tests on 3.6-3.8 so 3.5 compatibility is not guaranteed. We probably use features that python 3.5 doesnt support.
