### ISSUE TITLE
TypeError: Tuple or struct_time argument required

### ISSUE THREAD

**Issue by ssaranathan** [py-pa/django-minio-storage#95]
Hi,
I am getting the following error when Django Pod comes up in my kubernetes cluster.  Any idea what could be wrong ?
I am using django-minio-storage==0.3.7

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 263, in delete_file
    target_last_modified = self.storage.get_modified_time(prefixed_path)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 230, in get_modified_time
    dt = self.modified_time(name)
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 297, in modified_time
    return datetime.datetime.fromtimestamp(mktime(info.last_modified))
TypeError: Tuple or struct_time argument required

**Comment by brianhelba** [comment]
The code `datetime.datetime.fromtimestamp(mktime(info.last_modified))` was removed by #120. I don't think it's possible for this error to reoccur.
