### ISSUE TITLE
SSL Verification error inspite of having valid verified certificates

### ISSUE THREAD

**Issue by ssaranathan** [py-pa/django-minio-storage#96]
Hi Team,
I am hoping someone can help.  I am stuck with an issue in our Production servers.  Inspite of having a valid Verified Certificate from digicert, I am seeing this error when the Django container comes up:

`Try running with a higher verbosity level like: -v2 or -v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 410, in __init__
    object_metadata=object_metadata,
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 75, in __init__
    self._init_check()
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 93, in _init_check
    elif not self.client.bucket_exists(self.bucket_name):
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 431, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1984, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1919, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1950, in _get_bucket_location
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  [Previous line repeated 1 more times]
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='***ibm.com', port=443): Max retries exceeded with url: /local-static?location= (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))`

**Comment by ssaranathan** [comment]
@thomasf , @jhpinson , @rafaelsierra , @jamie-34254 is this something you can help us with ?  Thank you.

**Comment by ssaranathan** [comment]
K8s Pod was looking at wrong certificates.  This can be closed.

**Comment by RakeshAMD** [comment]
Could you please tell where we need to place the certificates for ubuntu?
I placed it under `/usr/local/share/ca-certificates` and ran `update-ca-certificates`. 
This imported certificates to `/etc/ssl/certs`. Still not working 

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='REDACTED', port=443): Max retries exceeded with url: /REDACTED-static?location= 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```
